# This is a dev docker-compose file which exports your wiki on localhost:8087
services:
  mediawiki:
    build: .
    volumes:
      - ./data/images:/images/2024
      - ./data/config:/config/2024
    ports:
      - 8087:80
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mediawiki
  db:
    image: "postgres:16.1-alpine"
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_USER=wiki
      - POSTGRES_PASSWORD=wiki
    networks:
      - mediawiki
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 30s
      start_interval: 1s
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  mediawiki:
