# This is a dev docker-compose file which exports your wiki on localhost:8087
version: '3'
services:
  mediawiki:
    build: .
    volumes:
      - ./data/images:/images
      - ./data/config:/config
    environment:
      URL_PREFIX:
    ports:
      - 8087:80
    links:
      - db
    depends_on:
      - db
  db:
    image: "postgres:16.1-alpine"
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_USER=wiki
      - POSTGRES_PASSWORD=wiki
